# Generated by Django 2.1.3 on 2018-11-01 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Voiture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no_serie', models.IntegerField()),
                ('marque', models.CharField(max_length=25)),
                ('modele', models.CharField(max_length=25)),
                ('couleur', models.CharField(choices=[('Bl', 'Bleu'), ('Ro', 'Rouge'), ('Ja', 'Jaune'), ('No', 'Noir'), ('Blc', 'Blanc'), ('Gr', 'Gris'), ('Ve', 'Vert')], max_length=4)),
                ('annee', models.DateField()),
                ('poid', models.IntegerField()),
                ('prix', models.FloatField()),
            ],
        ),
    ]
