# Generated by Django 2.1.3 on 2018-11-01 22:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('magasin', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='voiture',
            old_name='poid',
            new_name='poids',
        ),
    ]
